 export const cheeseData = [
  { "title": "Camembert", "rate": 8,},
  { "title": "Cheddar", "rate": 7 },
  { "title": "Gouda", "rate": 9 },
  { "title": "Brie", "rate": 6 },
  { "title": "Roquefort", "rate": 8 },
  { "title": "Parmesan", "rate": 7 },
  { "title": "Mozzarella", "rate": 8 },
  { "title": "Gruyère", "rate": 9 },
  { "title": "Feta", "rate": 6 },
  { "title": "Emmental", "rate": 7 },
  { "title": "Gorgonzola", "rate": 8 },
  { "title": "Havarti", "rate": 9 },
  { "title": "Monterey Jack", "rate": 7 },
  { "title": "Provolone", "rate": 8 },
  { "title": "Edam", "rate": 5 },
  { "title": "Manchego", "rate": 7 },
  { "title": "Blue Cheese", "rate": 8 },
  { "title": "Colby", "rate": 9 },
  { "title": "Swiss", "rate": 2 },
  { "title": "Muenster", "rate": 7 },
  { "title": "Pepper Jack", "rate": 6 },
  { "title": "Boursault", "rate": 8 },
  { "title": "Limburger", "rate": 9 },
  { "title": "Asiago", "rate": 7 },
  { "title": "Fontina", "rate": 8 },
  { "title": "Cottage Cheese", "rate": 6 },
  { "title": "Ricotta", "rate": 7 },
  { "title": "Boursin", "rate": 3 },
  { "title": "Gruyère", "rate": 9 },
  { "title": "Picodon", "rate": 10 },
  { "title": "Munster", "rate": 7 },
  { "title": "Cambozola", "rate": 8 },
  { "title": "Lancashire", "rate": 6 },
  { "title": "Monchego", "rate": 7 },
  { "title": "Red Leicester", "rate": 4 },
  { "title": "Double Gloucester", "rate": 3 },
  { "title": "Stilton", "rate": 7 },
  { "title": "Wensleydale", "rate": 6 },
  { "title": "Caerphilly", "rate": 4 },
  { "title": "Sage Derby", "rate": 8 },
  { "title": "Bel Paese", "rate": 5 },
  { "title": "Brick Cheese", "rate": 7 },
  { "title": "Havarti", "rate": 8 },
  { "title": "Jarlsberg", "rate": 4 },
  { "title": "Pont-l'Évêque", "rate": 8 },
  { "title": "Quark", "rate": 5 },
  { "title": "Teleme", "rate": 7 },
  { "title": "Livarot", "rate": 8 },
  { "title": "Fromager d'Affinois", "rate": 9 },
  { "title": "Taleggio", "rate": 7 },
  { "title": "Roquefort", "rate": 8 }
]
