const filmsData = [
  {
    url: "https://image.tmdb.org/t/p/w500/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    id: 238,
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 95.013,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "Le Parrain",
    rate: 8.7,
    vote_count: 18651,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    id: 466420,
    original_language: "en",
    original_title: "Killers of the Flower Moon",
    overview:
      "Au début du XXème siècle, le pétrole a apporté la fortune au peuple Osage qui, du jour au lendemain, est devenu l’un des plus riches du monde. La richesse de ces Amérindiens attire aussitôt la convoitise de Blancs peu recommandables qui intriguent, soutirent et volent autant d’argent Osage que possible avant de recourir au meurtre…",
    popularity: 1805.975,
    poster_path: "/t51ReMWxWcAOqKrGKw29OK2WhNz.jpg",
    release_date: "2023-10-18",
    title: "Killers of the Flower Moon",
    rate: 7.6,
    vote_count: 1351,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
    id: 897087,
    original_language: "en",
    original_title: "Freelance",
    overview:
      "Un agent des forces spéciales décide de prendre sa retraite de l’armée et de fonder une famille aux États-Unis. Après plusieurs années d’efforts pour se conformer à la vie en banlieue, il décide de sortir de sa retraite et d’accepter un contrat pour assurer la sécurité d’une journaliste alors qu’elle interviewe un dictateur sud-américain. Lorsqu’un coup d’État militaire éclate en plein milieu de l’interview, les voici tous trois contraints de s‘enfuir dans la jungle où ils doivent survivre aux éléments, aux militaires et les uns aux autres.",
    popularity: 1405.909,
    poster_path: "/sUhK63JNkcnq9tfcy6jLaXgN33x.jpg",
    release_date: "2023-10-05",
    title: "Freelance",
    rate: 6.3,
    vote_count: 251,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/jVFeUR259RcW57mzhqJogV3QnLa.jpg",
    id: 656156,
    original_language: "ko",
    original_title: "보호자",
    overview:
      "Après 10 ans d'incarcération au nom de son employeur, tout ce que Su-hyuk veut, c'est une vie normale - une vie qu'il espère inclure son ancienne petite amie, Min-seo, et leur fille, In-bi. Mais une fois que vous avez pénétré les échelons supérieurs du monde souterrain, la normalité peut s'avérer difficile à trouver. Entre-temps, au cours de la dernière décennie, l'employeur de Su-hyuk a adopté un air de légitimité. De nos jours, les vieux gangs volent et assassinent au nom du développement urbain. Et ils veulent que Su-hyuk, réticent, à bord.",
    popularity: 1096.115,
    poster_path: "/2XwxhT1acqFHBPaVDvriX7iuul3.jpg",
    release_date: "2023-08-15",
    title: "보호자",
    rate: 6.0,
    vote_count: 12,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/ixhr0YVs0Du0fPIYQSYYOIf3j0R.jpg",
    id: 854648,
    original_language: "en",
    original_title: "Robot Apocalypse",
    overview:
      "Lorsqu'une intelligence artificielle devient puissante, elle cible les systèmes des armes militaires de par le monde dans le seul but de détruire l'humanité. La hackeuse experte Tara tente d'arrêter la machine, mais cette dernière la désigne comme une terroriste devant être exterminée. Avec une cible dans le dos, Tara doit maintenant demander de l’aide à son réseau de mercenaires afin de pouvoir détruire la machine.",
    popularity: 1576.949,
    poster_path: "/kI8DywZXnHWWFjkIH2TF6lKZ9ag.jpg",
    release_date: "2021-07-26",
    title: "Robotapocalypse",
    rate: 5.9,
    vote_count: 21,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
    id: 901362,
    original_language: "en",
    original_title: "Trolls Band Together",
    overview:
      "Après deux films à se tourner autour pour finalement tomber dans les bras l’un de l’autre, Poppy et Branch sont officiellement en couple (#broppy)! Alors qu’ils n’ont plus de secrets l’un pour l’autre, Poppy fait une découverte incroyable relative au passé de Branch. À l’époque, avec ses quatre frères, Floyd, John Dory, Spruce et Clay, ils formaient le Boys Band le plus en vogue du moment, les BroZone. Alors qu’il n’était qu’un enfant, le groupe s’est séparé, tout comme la famille et depuis Branch n’a jamais revu ses frères.",
    popularity: 951.842,
    poster_path: "/r5uiTUeqoERL66fNgtPVbTViHml.jpg",
    release_date: "2023-10-12",
    title: "Les Trolls 3",
    rate: 7.1,
    vote_count: 346,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
    id: 787699,
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Basé sur le personnage extraordinaire au centre de Charlie et la chocolaterie, le livre pour enfants le plus emblématique de Roald Dahl est l'un des livres pour enfants les plus vendus de tous les temps, 'Wonka' raconte l'histoire merveilleuse de la façon dont le plus grand inventeur, magicien et chocolatier est devenu le bien-aimé Willy Wonka que nous connaissons aujourd'hui.",
    popularity: 1060.11,
    poster_path: "/6k9MDSPvsUjFIw311dAfpPHovmG.jpg",
    release_date: "2023-12-06",
    title: "Wonka",
    rate: 7.1,
    vote_count: 125,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg",
    id: 726209,
    original_language: "en",
    original_title: "Leave the World Behind",
    overview:
      "Amanda et son mari Clay louent une luxueuse villa pour y passer le week-end avec leurs enfants Archie et Rose. Leurs vacances sont bientôt interrompues lorsque deux inconnus G.H. et sa fille Ruth débarquent chez eux la nuit, annonçant une mystérieuse cyberattaque et cherchant à se réfugier dans cette maison qu'ils prétendent leur appartenir. Les deux familles affrontent alors une menace qui se rapproche inexorablement, obligeant chacun à reconsidérer sa place dans un monde qui s'écroule.",
    popularity: 1023.938,
    poster_path: "/m8L9D17fnfBIxtL8IPZuX6gzJTu.jpg",
    release_date: "2023-11-22",
    title: "Le Monde après nous",
    rate: 6.7,
    vote_count: 591,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg",
    id: 1075794,
    original_language: "en",
    original_title: "Leo",
    overview:
      "Leo, un lézard blasé de 74 ans, vit dans une salle de classe en Floride depuis des décennies, avec une tortue pour copain de terrarium. Aussi, quand il apprend qu'il n'a plus qu'une année à vivre, Leo décide de s'enfuir pour découvrir la vie en liberté. Mais les petits écoliers anxieux le retiennent, craignant notamment l'arrivée d'une méchante professeure remplaçante. La liste des choses à faire absolument par le vieux lézard pendant sa dernière année de vie va s'avérer des plus étranges, mais aussi des plus gratifiantes…",
    popularity: 844.255,
    poster_path: "/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
    release_date: "2023-11-17",
    title: "Leo",
    rate: 7.6,
    vote_count: 535,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      'En 1942, convaincus que l\'Allemagne nazie est en train de développer une arme nucléaire, les États-Unis initient, dans le plus grand secret, le "Projet Manhattan" destiné à mettre au point la première bombe atomique de l’histoire. Pour piloter ce dispositif, le gouvernement engage J. Robert Oppenheimer, brillant physicien, qui sera bientôt surnommé "le père de la bombe atomique". C\'est dans le laboratoire ultra-secret de Los Alamos, au cœur du désert du Nouveau-Mexique, que le scientifique et son équipe mettent au point une arme révolutionnaire dont les conséquences, vertigineuses, continuent de peser sur le monde actuel…',
    popularity: 818.431,
    poster_path: "/boAUuJBeID7VNp4L7LNMQs8mfQS.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    rate: 8.1,
    vote_count: 5377,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/mIpdOcss3oedSYB8juiSXg89uLL.jpg",
    id: 479753,
    original_language: "en",
    original_title: "Shockwave: Countdown to Disaster",
    overview:
      "Kate est une jeune chercheuse qui a découvert l'existence d'une arme à résonance qui pourrait provoquer la fin de monde si elle tombait entre de mauvaises mains. C'est avec l'aide de son mari Rob, professeur à l'université et spécialiste des failles sismiques et de sa fille qu'elle va tenter de neutraliser le dispositif Hellstorm, nom de cette arme secrète qui a déjà dévasté Paris, causant des centaines de milliers de morts.",
    popularity: 668.619,
    poster_path: "/sBD608VF4TcFHmP7SuC0OcvZQ0b.jpg",
    release_date: "2017-09-02",
    title: "Les codes de l'apocalypse",
    rate: 5.6,
    vote_count: 55,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/3xvdNyZ9WsVJpyeGhm85fukeZz4.jpg",
    id: 1001835,
    original_language: "en",
    original_title: "Wifelike",
    overview:
      "Meredith, humaine artificielle désignée comme compagne de William, a été conçue pour se comporter comme sa défunte épouse. Cependant, une organisation tente de saboter sa programmation.",
    popularity: 599.911,
    poster_path: "/tea2gDZPxw0wfKC2S2VRWHagtt4.jpg",
    release_date: "2022-08-12",
    title: "Wifelike",
    rate: 7.0,
    vote_count: 198,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/jhpsTzbXEu5bkCPmBqxv7vUTjIT.jpg",
    id: 566810,
    original_language: "en",
    original_title: "Dragon Kingdom",
    overview:
      "Pour sauver leur royaume et déjouer les plans insidieux de la puissante armée des Dark Lords et leurs dragons, la Princesse Elizabeth, future Reine, accompagnée d’un groupe de valeureux guerriers sont contraints de traverser les terres interdites. Pour qu’elle puisse rejoindre son père le Roi et lui succéder sur le trône, ils vont devoir combattre les redoutables et dangereuses créatures mythiques du royaume des ténèbres.",
    popularity: 721.477,
    poster_path: "/xBvTRV8VO4OpbUK8NcIvC3zHpMH.jpg",
    release_date: "2018-11-26",
    title: "Reign of Fire",
    rate: 5.7,
    vote_count: 41,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
    id: 507089,
    original_language: "en",
    original_title: "Five Nights at Freddy's",
    overview:
      "Mike, jeune homme perturbé, s’occupe de sa sœur Abby, âgée de 10 ans. Il est toujours hanté par la disparition, jamais élucidée, de son petit frère, survenue il y a une dizaine d’années. Récemment licencié, il a absolument besoin de retrouver un emploi pour ne pas perdre la garde d’Abby. Il accepte donc un poste de gardien de nuit, dans un restaurant désaffecté : Freddy Fazbear’s Pizzeria. Mais Mike ne tarde pas à comprendre que les apparences y sont terriblement trompeuses. Avec l’aide de Vanessa Shelly, agent de police, il est confronté, la nuit, à des phénomènes surnaturels inexplicables et bascule dans un univers cauchemardesque...",
    popularity: 632.08,
    poster_path: "/tEY81I7lpiHaLJa7AZ3O4vWXmJo.jpg",
    release_date: "2023-10-25",
    title: "Five Nights at Freddy's",
    rate: 7.8,
    vote_count: 2795,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Après bien des missions et contre toute attente, Dom Toretto et sa famille ont su déjouer, devancer, surpasser et distancer tous les adversaires qui ont croisé leur route. Ils sont aujourd’hui face à leur ennemi le plus terrifiant et le plus intime : émergeant des brumes du passé, ce revenant assoiffé de vengeance est bien déterminé à décimer la famille en réduisant à néant tout ce à quoi, et surtout à qui Dom ait jamais tenu.",
    popularity: 576.426,
    poster_path: "/piYNJlLvSlXYnXh6ZoKzhPdrMfV.jpg",
    release_date: "2023-05-17",
    title: "Fast & Furious X",
    rate: 7.1,
    vote_count: 4447,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg",
    id: 695721,
    original_language: "en",
    original_title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    overview:
      'Préquelle de Hunger Games se déroulant 64 ans plus tôt, dans les années qui ont suivi la période des "Jours sombres", la première rébellion ratée à Panem…  De nombreuses années avant de devenir Président de Panem, le jeune Coriolanus Snow est choisi comme mentor du district 12 lors des nouveaux Hunger Games.',
    popularity: 545.352,
    poster_path: "/rMKxQ2B54BIhc7BG8I9CmQuhsFT.jpg",
    release_date: "2023-11-15",
    title: "Hunger Games : La ballade du serpent et de l'oiseau chanteur",
    rate: 7.2,
    vote_count: 699,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg",
    id: 670292,
    original_language: "en",
    original_title: "The Creator",
    overview:
      "Alors qu'une future guerre entre la race humaine et l'intelligence artificielle fait rage, l'ancien agent des forces spéciales Joshua est recruté pour traquer et tuer le Créateur, l'insaisissable architecte de l'IA avancée.",
    popularity: 522.412,
    poster_path: "/pP1cyoXFc5Br1Sg21uORSN49yyu.jpg",
    release_date: "2023-09-27",
    title: "The Creator",
    rate: 7.1,
    vote_count: 1414,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/4MUfDtBqUFqotGF5RJOfNfoBTLo.jpg",
    id: 951546,
    original_language: "en",
    original_title: "Reign of Chaos",
    overview:
      "Lorsque le monde est saisi par un fléau déchaîné par le méchant Chaos et les humains sont transformés en créatures enragées, trois jeunes femmes descendantes d'une déesse sont chargées de sauver l'humanité.",
    popularity: 529.038,
    poster_path: "/nTMmpvR9TyV631tpFr4FtYxG0FC.jpg",
    release_date: "2022-04-12",
    title: "Reign of Chaos",
    rate: 5.6,
    vote_count: 28,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/evxXVJtomJJbAXcDxF6wsCJzVDe.jpg",
    id: 1019836,
    original_language: "en",
    original_title: "Christmas Bloody Christmas",
    overview:
      "C'est la veille de Noël. La propriétaire d'un magasin de disques, Tori Tooms, souhaite faire la fête, jusqu'à ce que le Père Noël robotisé d'un magasin de jouets voisin se dérègle et rende sa nuit plus que compliquée que prévu. En effet, ce \" Père Noël \" se lance dans une folie meurtrière...",
    popularity: 544.396,
    poster_path: "/97PaQ7r4H3y0x9RTXusfedmzf86.jpg",
    release_date: "2022-10-05",
    title: "Christmas Bloody Christmas",
    rate: 5.6,
    vote_count: 145,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/LfUXJQOhBa0cfQsGnYwuSUaHId.jpg",
    id: 940175,
    original_language: "en",
    original_title: "A Tale of Two Guns",
    overview: "",
    popularity: 529.134,
    poster_path: "/kT3Zy7kOQERHnpEHT1wMwXEpJsk.jpg",
    release_date: "2022-02-17",
    title: "A Tale of Two Guns",
    rate: 6.3,
    vote_count: 8,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/h3X1YZXNeklLNKRVOS6DHGRosog.jpg",
    id: 287903,
    original_language: "en",
    original_title: "Krampus",
    overview:
      "Quand Max voit sa famille peu exemplaire se disputer à l'approche de Noël, le garçon décide d'ignorer la célébration, sans se rendre compte que ce manquement à la tradition va provoquer les foudres de Krampus, un démon ancestral bien décidé à punir les réfractaires. La situation tourne en enfer quand les figures de Noël prennent monstrueusement vie, lançant l'assaut sur la maison de Max et forçant les membres de sa famille à s'entraider s'ils espèrent sauver leur peau.",
    popularity: 536.224,
    poster_path: "/eefEFpgdaGH9udEm3hefnbXQnsh.jpg",
    release_date: "2015-11-26",
    title: "Krampus",
    rate: 6.1,
    vote_count: 1966,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg",
    genre_ids: [28, 12, 53],
    id: 299054,
    original_language: "en",
    original_title: "Expend4bles",
    overview:
      "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
    popularity: 478.791,
    poster_path: "/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg",
    release_date: "2023-09-15",
    title: "Expend4bles",
    rate: 6.4,
    vote_count: 890,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/lDlVgD9IGAmki7CgIlH5eYUwrhW.jpg",
    genre_ids: [28, 12, 878],
    id: 857879,
    original_language: "en",
    original_title: "Mount Adams",
    overview:
      "UFO investigators find themselves fighting for survival as alien monsters hunt them on the slopes of Mount Adams.",
    popularity: 629.606,
    poster_path: "/nddTKKAu6z771duaxr1D32pHZ8j.jpg",
    release_date: "2021-07-21",
    title: "Mount Adams",
    rate: 5.5,
    vote_count: 0,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
    genre_ids: [28, 53],
    id: 575264,
    original_language: "en",
    original_title: "Mission: Impossible - Dead Reckoning Part One",
    overview:
      "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
    popularity: 408.933,
    poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    release_date: "2023-07-08",
    title: "Mission: Impossible - Dead Reckoning Part One",
    rate: 7.5,
    vote_count: 2678,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/iaMIylLoN7Y3CvrA0pg2ZFKjk26.jpg",
    genre_ids: [10752, 18, 28],
    id: 1047925,
    original_language: "en",
    original_title: "Come Out Fighting",
    overview:
      "In WWII, a squad of U.S. African-American soldiers are sent on a rescue mission behind enemy lines to locate their lost commanding officer and a downed fighter pilot.",
    popularity: 429.108,
    poster_path: "/sERwJxz0sqsbcUoTm66l9pI6HcH.jpg",
    release_date: "2023-05-19",
    title: "Come Out Fighting",
    rate: 5.1,
    vote_count: 26,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg",
    genre_ids: [878, 12, 28],
    id: 609681,
    original_language: "en",
    original_title: "The Marvels",
    overview:
      "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
    popularity: 465.513,
    poster_path: "/Ag3D9qXjhJ2FUkrlJ0Cv1pgxqYQ.jpg",
    release_date: "2023-11-08",
    title: "The Marvels",
    rate: 6.5,
    vote_count: 677,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/by7XJXrMGKIhV2fbQm9QRDfJxxI.jpg",
    genre_ids: [878, 28, 53],
    id: 845844,
    original_language: "en",
    original_title: "Extraction Point",
    overview:
      "An alien visitor must race against time to reach his extraction point after his UFO is forced to crash down on Earth.",
    popularity: 401.305,
    poster_path: "/1djkxHjE3Z2Wk30nrIYm3tj19DO.jpg",
    release_date: "2021-06-29",
    title: "Extraction Point",
    rate: 5.6,
    vote_count: 36,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/oqbcmZJJ1EWkOPiGjqABaUN18rI.jpg",
    genre_ids: [16, 35, 10751],
    id: 1046032,
    original_language: "en",
    original_title: "The Bad Guys: A Very Bad Holiday",
    overview:
      "To keep their annual Holiday Heist-tacular afloat, Mr. Wolf and his crew of animal outlaws will have to restore the whole city's Christmas spirit — fast!",
    popularity: 373.373,
    poster_path: "/atBDD05PbVDI2lm2OUy1KFQpzen.jpg",
    release_date: "2023-11-30",
    title: "The Bad Guys: A Very Bad Holiday",
    rate: 6.9,
    vote_count: 49,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg",
    genre_ids: [878, 27, 28],
    id: 940721,
    original_language: "ja",
    original_title: "ゴジラ-1.0",
    overview:
      "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?",
    popularity: 395.317,
    poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
    release_date: "2023-11-03",
    title: "Godzilla Minus One",
    rate: 8.3,
    vote_count: 115,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/lPzOcS88GQ7PwspTNUY8q6ACFOh.jpg",
    genre_ids: [28],
    id: 662167,
    original_language: "en",
    original_title: "Agent Jade Black",
    overview:
      "A skilled young female agent is tasked with capturing a rogue former agent before she can unleash a biological weapon starting with the wealthy and powerful purveyors of the international sex trade.",
    popularity: 364.299,
    poster_path: "/wGHaEtBz6AXqGVooaADB1tlyjBp.jpg",
    release_date: "2020-09-29",
    title: "Agent Jade Black",
    rate: 1.3,
    vote_count: 3,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/eM3mtxc9OMFghS9K0uDc9DWzIrD.jpg",
    genre_ids: [53, 80, 28, 18],
    id: 995206,
    original_language: "ja",
    original_title: "最後まで行く",
    overview:
      "After going to extremes to cover up an accident, a corrupt cop's life spirals out of control when he starts receiving threats from a mysterious witness.",
    popularity: 410.997,
    poster_path: "/zZFqGmhJMUiTuEJSneIbI7N5sCw.jpg",
    release_date: "2023-05-19",
    title: "Hard Days",
    rate: 6.9,
    vote_count: 20,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
    genre_ids: [16, 10751, 12, 14, 35],
    id: 502356,
    original_language: "en",
    original_title: "The Super Mario Bros. Movie",
    overview:
      "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
    popularity: 399.462,
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    release_date: "2023-04-05",
    title: "The Super Mario Bros. Movie",
    rate: 7.7,
    vote_count: 7421,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg",
    genre_ids: [16, 35, 10751, 14, 10749],
    id: 976573,
    original_language: "en",
    original_title: "Elemental",
    overview:
      "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
    popularity: 370.088,
    poster_path: "/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
    release_date: "2023-06-14",
    title: "Elemental",
    rate: 7.7,
    vote_count: 3196,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
    genre_ids: [35, 12, 14],
    id: 346698,
    original_language: "en",
    original_title: "Barbie",
    overview:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    popularity: 354.801,
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    release_date: "2023-07-19",
    title: "Barbie",
    rate: 7.1,
    vote_count: 6250,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/5mzr6JZbrqnqD8rCEvPhuCE5Fw2.jpg",
    genre_ids: [28, 878, 27],
    id: 615656,
    original_language: "en",
    original_title: "Meg 2: The Trench",
    overview:
      "An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.",
    popularity: 355.045,
    poster_path: "/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg",
    release_date: "2023-08-02",
    title: "Meg 2: The Trench",
    rate: 6.7,
    vote_count: 2662,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/AucuqDaUW4z1oT5XyL71qwRY2F6.jpg",
    genre_ids: [27, 53],
    id: 983507,
    original_language: "no",
    original_title: "Meg, deg & Frank",
    overview:
      "Christian - a millionaire heir, meets Sigrid - a young student, on a dating app. They hit it off quickly, but there's only one problem: Christian lives with Frank, a man who dresses up and constantly acts like a dog.",
    popularity: 516.213,
    poster_path: "/9DPG1gxLwV2oyFdHq3SnISsWbse.jpg",
    release_date: "2022-06-03",
    title: "Good Boy",
    rate: 6.8,
    vote_count: 99,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/biRLtgt3t8MwxeLRRJkf1BsHoeq.jpg",
    genre_ids: [28, 53],
    id: 1060090,
    original_language: "en",
    original_title: "The Collective",
    overview:
      "A group of righteous assassins called The Collective take aim at a highly sophisticated human trafficking ring backed by a network of untouchable billionaires. With their backs against the wall, The Collective has no choice but to put their most important mission in the hands of rookie assassin, Sam Alexander.",
    popularity: 373.959,
    poster_path: "/Ah9H6Sj434nJiZpTPQrovHaEePV.jpg",
    release_date: "2023-08-04",
    title: "The Collective",
    rate: 5.3,
    vote_count: 31,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
    genre_ids: [28, 12, 878],
    id: 667538,
    original_language: "en",
    original_title: "Transformers: Rise of the Beasts",
    overview:
      "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
    popularity: 359.107,
    poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    release_date: "2023-06-06",
    title: "Transformers: Rise of the Beasts",
    rate: 7.4,
    vote_count: 3681,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/m06dOSnShSmGfVgz4iSQhx6bzWv.jpg",
    genre_ids: [28, 12, 878],
    id: 775244,
    original_language: "ar",
    original_title: "موسى",
    overview:
      "An engineering college student invents the first of its kind robot in the Middle East, in an attempt to avenge his father's death and achieve justice, which gets him pursued by the authorities.",
    popularity: 334.813,
    poster_path: "/voo0uaAVCGYgAAeJEf5peFNPOAI.jpg",
    release_date: "2021-08-11",
    title: "Mousa",
    rate: 6.8,
    vote_count: 24,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/tC78Pck2YCsUAtEdZwuHYUFYtOj.jpg",
    genre_ids: [28, 53, 80],
    id: 926393,
    original_language: "en",
    original_title: "The Equalizer 3",
    overview:
      "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
    popularity: 351.32,
    poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg",
    release_date: "2023-08-30",
    title: "The Equalizer 3",
    rate: 7.4,
    vote_count: 1864,
  },
  {
    url: "https://image.tmdb.org/t/p/w500/vRx6kzCItpqwnYCcj2z8qf70gv3.jpg",
    genre_ids: [28, 18, 10749],
    id: 10908,
    original_language: "en",
    original_title: "Inferno",
    overview:
      "Eddie Lomax (Jean-Claude Van Damme) is a drifter who has been in a suicidal funk since the death of his close friend Johnny (Danny Trejo). Riding his motorcycle into a small desert town where Johnny once lived, Lomax is confronted by a gang of toughs, who beat him and steal his bike. However, Lomax is not a man to take an injustice lying down, and soon he begins exacting a violent revenge on the men who stole his motorcycle, with local handyman Jubal Early (Pat Morita) lending a hand and several area ladies offering aid and comfort.",
    popularity: 320.774,
    poster_path: "/dFlI0Vb4JOsRXG1JSS2Ufs6Sp8k.jpg",
    release_date: "1999-09-25",
    title: "Inferno",
    rate: 6.1,
    vote_count: 281,
  },
];

export default filmsData;
