export const filmsData = [
  {
    "url": "https://image.tmdb.org/t/p/w500/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    "id": 238,
    "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    "popularity": 95.013,
    "poster_path": "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    "release_date": "1972-03-14",
    "title": "Le Parrain",
    "rate": 8.7,
    "vote_count": 18651
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    "id": 278,
    "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    "popularity": 90.97,
    "poster_path": "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    "release_date": "1994-09-23",
    "title": "Les Évadés",
    "rate": 8.6,
    "vote_count": 24618
  },
  {

    "url": "https://image.tmdb.org/t/p/w500/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    "id": 424,
    "overview": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    "popularity": 63.161,
    "poster_path": "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    "release_date": "1993-12-15",
    "title": "Schindler's List",
    "rate": 8.6,
    "vote_count": 14561
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
    "id": 19404,
    "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    "popularity": 32.221,
    "poster_path": "/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg",
    "release_date": "1995-10-20",
    "title": "Dilwale Dulhania Le Jayenge",
    "rate": 8.6,
    "vote_count": 4247
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    "id": 389,
    "overview": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    "popularity": 42.663,
    "poster_path": "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    "release_date": "1957-04-10",
    "title": "12 Angry Men",
    "rate": 8.5,
    "vote_count": 7637
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    "id": 129,
    "overview": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    "popularity": 79.108,
    "poster_path": "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    "release_date": "2001-07-20",
    "title": "Spirited Away",
    "rate": 8.5,
    "vote_count": 14882
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    "id": 496243,
    "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    "popularity": 82.988,
    "poster_path": "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    "release_date": "2019-05-30",
    "title": "Parasite",
    "rate": 8.5,
    "vote_count": 16397
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    "id": 372058,
    "overview": "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    "popularity": 82.693,
    "poster_path": "/q719jXXEzOoYaps6babgKnONONX.jpg",
    "release_date": "2016-08-26",
    "title": "Your Name.",
    "rate": 8.5,
    "vote_count": 10275
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    "id": 155,
    "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    "popularity": 94.684,
    "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "release_date": "2008-07-16",
    "title": "The Dark Knight",
    "rate": 8.5,
    "vote_count": 30582
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
    "id": 497,
    "overview": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    "popularity": 63.957,
    "poster_path": "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    "release_date": "1999-12-10",
    "title": "The Green Mile",
    "rate": 8.5,
    "vote_count": 15909
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    "id": 680,
    "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    "popularity": 66.493,
    "poster_path": "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    "release_date": "1994-09-10",
    "title": "Pulp Fiction",
    "rate": 8.5,
    "vote_count": 25855
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
    "id": 13,
    "overview": "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    "popularity": 64.354,
    "poster_path": "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    "release_date": "1994-06-23",
    "title": "Forrest Gump",
    "rate": 8.5,
    "vote_count": 25375
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/eoCSp75lxatmIa6aGqfnzwtbttd.jpg",
    "id": 429,
    "overview": "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    "popularity": 55.21,
    "poster_path": "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    "release_date": "1966-12-23",
    "title": "The Good, the Bad and the Ugly",
    "rate": 8.5,
    "vote_count": 7732
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    "id": 122,
    "overview": "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    "popularity": 92.676,
    "poster_path": "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    "release_date": "2003-12-01",
    "title": "The Lord of the Rings: The Return of the King",
    "rate": 8.5,
    "vote_count": 22266
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/sw7mordbZxgITU877yTpZCud90M.jpg",
    "id": 769,
    "overview": "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    "popularity": 58.593,
    "poster_path": "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    "release_date": "1990-09-12",
    "title": "GoodFellas",
    "rate": 8.5,
    "vote_count": 11705
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
    "id": 637,
    "overview": "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    "popularity": 45.782,
    "poster_path": "/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg",
    "release_date": "1997-12-20",
    "title": "Life Is Beautiful",
    "rate": 8.5,
    "vote_count": 12199
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
    "id": 11216,
    "overview": "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    "popularity": 36.264,
    "poster_path": "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
    "release_date": "1988-11-17",
    "title": "Cinema Paradiso",
    "rate": 8.5,
    "vote_count": 3942
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg",
    "id": 12477,
    "overview": "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    "popularity": 0.6,
    "poster_path": "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    "release_date": "1988-04-16",
    "title": "Grave of the Fireflies",
    "rate": 8.5,
    "vote_count": 4845
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
    "id": 346,
    "popularity": 29.642,
    "poster_path": "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    "release_date": "1954-04-26",
    "title": "Seven Samurai",
    "rate": 8.5,
    "vote_count": 3220
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/xw1gA0lm0AEhGLoR6sE8IYCQAV4.jpg",
    "id": 40096,
    "overview": "The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.",
    "popularity": 9.039,
    "poster_path": "/m8eFedsS7vQCZCS8WGp5n1bVD0q.jpg",
    "release_date": "2000-09-15",
    "title": "A Dog's Will",
    "rate": 8.4,
    "vote_count": 1009
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/nv5wwZou159v5OC61i4ElR7OqyY.jpg",
    "id": 4935,
    "overview": "Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.",
    "popularity": 64.257,
    "poster_path": "/6pZgH10jhpToPcf0uvyTCPFhWpI.jpg",
    "release_date": "2004-09-09",
    "title": "Howl's Moving Castle",
    "rate": 8.4,
    "vote_count": 8695
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/l5K9elugftlcyIHHm4nylvsn26X.jpg",
    "id": 255709,
    "overview": "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
    "popularity": 34.308,
    "poster_path": "/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
    "release_date": "2013-10-02",
    "title": "Hope",
    "rate": 8.4,
    "vote_count": 570
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/wxaBkuqVIgImjRHEMJoxL9Lq6i8.jpg",
    "id": 995133,
    "overview": "The unlikely friendship of a boy, a mole, a fox and a horse traveling together in the boy’s search for home.",
    "popularity": 23.12,
    "poster_path": "/oQRgyQCzcyZvE6w5heM9ktVY0LT.jpg",
    "release_date": "2022-12-25",
    "title": "The Boy, the Mole, the Fox and the Horse",
    "rate": 8.4,
    "vote_count": 391
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg",
    "id": 1891,
    "overview": "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
    "popularity": 37.987,
    "poster_path": "/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg",
    "release_date": "1980-05-20",
    "title": "The Empire Strikes Back",
    "rate": 8.4,
    "vote_count": 15750
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/zcc0My3G4SYR72VuEYHNcUWkkW0.jpg",
    "id": 121,
    "overview": "Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
    "popularity": 76.41,
    "poster_path": "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    "release_date": "2002-12-18",
    "title": "The Lord of the Rings: The Two Towers",
    "rate": 8.4,
    "vote_count": 20239
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/dVr11o9or7AS8AMPfwjSpEU83iU.jpg",
    "id": 423,
    "overview": "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
    "popularity": 41.731,
    "poster_path": "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
    "release_date": "2002-09-17",
    "title": "The Pianist",
    "rate": 8.4,
    "vote_count": 8331
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/vNXGrknx4GjWLgmuNTftWZluIUl.jpg",
    "id": 244786,
    "overview": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    "popularity": 43.49,
    "poster_path": "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    "release_date": "2014-10-10",
    "title": "Whiplash",
    "rate": 8.4,
    "vote_count": 13867
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg",
    "id": 807,
    "overview": "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the \"seven deadly sins\" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.",
    "popularity": 52.748,
    "poster_path": "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    "release_date": "1995-09-22",
    "title": "Se7en",
    "rate": 8.4,
    "vote_count": 19371
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    "id": 27205,
    "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    "popularity": 78.027,
    "poster_path": "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    "release_date": "2010-07-15",
    "title": "Inception",
    "rate": 8.4,
    "vote_count": 34461
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg",
    "id": 92321,
    "overview": "One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...",
    "popularity": 0.6,
    "poster_path": "/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg",
    "release_date": "2011-09-17",
    "title": "Hotarubi no Mori e",
    "rate": 8.4,
    "vote_count": 985
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/jBIMZ0AlUYuFNsKbd4L6FojWMoy.jpg",
    "id": 820067,
    "overview": "When five lovely young girls who hate studying hire part-time tutor Futaro, he guides not only their education but also their hearts. Time spent has brought them all closer, with feelings growing within the girls and Futaro. As they finish their third year of high school and their last school festival approaches, they set their sights on what’s next. Is there a future with one of them and Futaro?",
    "popularity": 62.104,
    "poster_path": "/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg",
    "release_date": "2022-05-20",
    "title": "The Quintessential Quintuplets Movie",
    "rate": 8.4,
    "vote_count": 327
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/zGs5tZOlvc9cprdcU6kDOVNpujf.jpg",
    "id": 567,
    "overview": "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
    "popularity": 35.617,
    "poster_path": "/qitnZcLP7C9DLRuPpmvZ7GiEjJN.jpg",
    "release_date": "1954-08-01",
    "title": "Rear Window",
    "rate": 8.4,
    "vote_count": 5881
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/9LSsSPbP715XT9B7acIZzantPyX.jpg",
    "id": 73,
    "overview": "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
    "popularity": 35.202,
    "poster_path": "/euypWkaYFOLW3e5rLIcTAjWnhhT.jpg",
    "release_date": "1998-07-01",
    "title": "American History X",
    "rate": 8.4,
    "vote_count": 10713
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/AfyuI3glMCBDFmNPj9PY6DwbgGp.jpg",
    "id": 18491,
    "overview": "The second of two theatrically released follow-ups to the Neon Genesis Evangelion series. Comprising of two alternate episodes which were first intended to take the place of episodes 25 and 26, this finale answers many of the questions surrounding the series, while also opening up some new possibilities.",
    "popularity": 33.522,
    "poster_path": "/j6G24dqI4WgUtChhWjfnI4lnmiK.jpg",
    "release_date": "1997-07-19",
    "title": "Neon Genesis Evangelion: The End of Evangelion",
    "rate": 8.3,
    "vote_count": 1375
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg",
    "id": 599,
    "overview": "A hack screenwriter writes a screenplay for a former silent film star who has faded into Hollywood obscurity.",
    "popularity": 21.152,
    "poster_path": "/sC4Dpmn87oz9AuxZ15Lmip0Ftgr.jpg",
    "release_date": "1950-08-10",
    "title": "Sunset Boulevard",
    "rate": 8.3,
    "vote_count": 2314
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg",
    "id": 274,
    "overview": "Clarice Starling is a top student at the FBI's training academy.  Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.  Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
    "popularity": 12.484,
    "poster_path": "/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    "release_date": "1991-02-14",
    "title": "The Silence of the Lambs",
    "rate": 8.3,
    "vote_count": 14981
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/aLqtWLA6NQHBwQHvHDq5z4EKUm0.jpg",
    "id": 533514,
    "overview": "As the world moves on from the war and technological advances bring changes to her life, Violet still hopes to see her lost commanding officer again.",
    "popularity": 28.398,
    "poster_path": "/s5sC5iWYCEeJwCLOMm1Z10Oso3d.jpg",
    "release_date": "2020-09-18",
    "title": "Violet Evergarden: The Movie",
    "rate": 8.3,
    "vote_count": 343
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/5qtOVAcBFogwktkseoZSfZVq6bx.jpg",
    "id": 3782,
    "overview": "Kanji Watanabe is a middle-aged man who has worked in the same monotonous bureaucratic position for decades. Learning he has cancer, he starts to look for the meaning of his life.",
    "popularity": 21.052,
    "poster_path": "/dgNTS4EQDDVfkzJI5msKuHu2Ei3.jpg",
    "release_date": "1952-10-09",
    "title": "Ikiru",
    "rate": 8.3,
    "vote_count": 977
  },
  {
    "url": "https://image.tmdb.org/t/p/w500/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg",
    "id": 128,
    "overview": "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
    "popularity": 42.625,
    "poster_path": "/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
    "release_date": "1997-07-12",
    "title": "Princess Mononoke",
    "rate": 8.3,
    "vote_count": 7207
  },
      {
        "url": "https://image.tmdb.org/t/p/w500/jsqR0qyGiaR4KLSASyPVTuNKj1U.jpg",
        "id": 1102551,
        "overview": "James Skinford plans to steal and flip a mystery truck to make some money and save his sick father, but his plans are thrown into chaos when he meets a woman with an immortal touch.",
        "popularity": 175.811,
        "poster_path": "/6YmqltcocUd35cvira6OzxQsoXW.jpg",
        "release_date": "2023-05-19",
        "title": "Skinford: Death Sentence",
        "rate": 4.7,
        "vote_count": 3
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/4Yon9Qmg3U4onL0OywXAHSkFTUG.jpg",
        "id": 1163045,
        "original_title": "Jagun Jagun",
        "overview": "A young man determined to become a powerful warrior joins an elite army, encountering the wrath of a maniacal warlord and the love of a fierce woman.",
        "popularity": 206.298,
        "poster_path": "/n0GXumEMtwgYj2M3YW4Iu0veYJg.jpg",
        "release_date": "2023-08-10",
        "title": "Jagun Jagun",
        "rate": 6.5,
        "vote_count": 43
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg",
        "id": 423108,
        "original_title": "The Conjuring: The Devil Made Me Do It",
        "overview": "Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
        "popularity": 200.764,
        "poster_path": "/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg",
        "release_date": "2021-05-25",
        "title": "The Conjuring: The Devil Made Me Do It",
        "rate": 7.5,
        "vote_count": 5388
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/3VjhZz7CrNSdKUIMYg4dVcyrRbb.jpg",
        "id": 1061656,
        "original_title": "Perpetrator",
        "overview": "Jonny Baptiste is a reckless teen sent to live with her estranged Aunt Hildie. On the event of her eighteenth birthday, she experiences a radical metamorphosis: a family spell that redefines her called Forevering. When several teen girls go missing at her new school, a mythically feral Jonny goes after the Perpetrator.",
        "popularity": 190.027,
        "poster_path": "/fjTI6czy62GCsoI7G7fKghSrH2x.jpg",
        "release_date": "2023-09-14",
        "title": "Perpetrator",
        "rate": 3.9,
        "vote_count": 11
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/8FhKnPpql374qyyHAkZDld93IUw.jpg",
        "id": 536437,
        "original_title": "Hypnotic",
        "overview": "A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.",
        "popularity": 197.59,
        "poster_path": "/mv362kHXz4Yr33wtQhqfcJWFM8G.jpg",
        "release_date": "2023-05-11",
        "title": "Hypnotic",
        "rate": 6.5,
        "vote_count": 557
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/xmhGjWA0NtNbnBlsLdOxGJ7J1h3.jpg",
        "id": 1118256,
        "original_title": "Keramat Tunggak",
        "overview": "Based on the true story of life in the Kramat Tunggak localization. Tells the story of commercial sex workers who live the hard night life as prostitutes.",
        "popularity": 118.157,
        "poster_path": "/A7Ii0tOvY77pSUTH2PaLeRk5eHW.jpg",
        "release_date": "2023-04-21",
        "title": "Keramat Tunggak",
        "rate": 10,
        "vote_count": 1
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/eTvN54pd83TrSEOz6wbsXEJktCV.jpg",
        "id": 882569,
        "original_title": "Guy Ritchie's The Covenant",
        "overview": "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.",
        "popularity": 190.936,
        "poster_path": "/kVG8zFFYrpyYLoHChuEeOGAd6Ru.jpg",
        "release_date": "2023-04-19",
        "title": "Guy Ritchie's The Covenant",
        "rate": 7.8,
        "vote_count": 1604
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/AioRI7M077BBR33VimFiyFop2Rc.jpg",
        "id": 1149381,
        "original_title": "Operacja: Soulcatcher",
        "overview": "A military contractor hired to seize a weapon that turns people into savage killers seeks revenge when his brother falls victim to the device.",
        "popularity": 192.041,
        "poster_path": "/l1f9JSPjCfNftigEii1SDK1g2b3.jpg",
        "release_date": "2023-08-02",
        "title": "Soulcatcher",
        "rate": 6.5,
        "vote_count": 183
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/kcHGf7yDJGrtCVMhqz0DVdvZg5A.jpg",
        "id": 1030987,
        "original_title": "Sympathy for the Devil",
        "overview": "After being forced to drive a mysterious passenger at gunpoint, a man finds himself in a high-stakes game of cat and mouse where it becomes clear that not everything is as it seems.",
        "popularity": 200.242,
        "poster_path": "/ozC9UaKaS0MXjMbCAHZJikszwV6.jpg",
        "release_date": "2023-07-20",
        "title": "Sympathy for the Devil",
        "rate": 6.3,
        "vote_count": 87
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg",
        "id": 758323,
        "original_title": "The Pope's Exorcist",
        "overview": "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
        "popularity": 186.746,
        "poster_path": "/jFC4LS5qTAT3PinzdEzINfu1CV9.jpg",
        "release_date": "2023-04-05",
        "title": "The Pope's Exorcist",
        "rate": 7.2,
        "vote_count": 1931
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/xh1Xjiu7Q0ORz3DbJjlwfC2KwVM.jpg",
        "id": 42968,
        "original_title": "La monja",
        "overview": "Years ago, a cruel and merciless nun turned a boarding school into a living hell for her students until they could no longer bear the abuse, and she mysteriously disappeared. Now the alumnae are being brutally murdered one by one.",
        "popularity": 167.011,
        "poster_path": "/2bDojliSLzGFwxlqQZodJAXHy7H.jpg",
        "release_date": "2005-11-03",
        "title": "The Nun",
        "rate": 5.5,
        "vote_count": 212
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/z7noaCJ4KtmhwHw7QcNtnMMo4Qy.jpg",
        "id": 345887,
        "original_title": "The Equalizer 2",
        "overview": "Robert McCall, who serves an unflinching justice for the exploited and oppressed, embarks on a relentless, globe-trotting quest for vengeance when a long-time girl friend is murdered.",
        "popularity": 130.933,
        "poster_path": "/cQvc9N6JiMVKqol3wcYrGshsIdZ.jpg",
        "release_date": "2018-07-19",
        "title": "The Equalizer 2",
        "rate": 6.7,
        "vote_count": 4630
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/zcySy6dnSmyqiichtDgO7AEeZoq.jpg",
        "id": 254128,
        "original_title": "San Andreas",
        "overview": "In the aftermath of a massive earthquake in California, a rescue-chopper pilot makes a dangerous journey across the state in order to rescue his estranged daughter.",
        "popularity": 176.001,
        "poster_path": "/2Gfjn962aaFSD6eST6QU3oLDZTo.jpg",
        "release_date": "2015-05-27",
        "title": "San Andreas",
        "rate": 6.2,
        "vote_count": 8020
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/wRxLAw4l17LqiFcPLkobriPTZAw.jpg",
        "id": 697843,
        "original_title": "Extraction 2",
        "overview": "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
        "popularity": 195.104,
        "poster_path": "/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
        "release_date": "2023-06-09",
        "title": "Extraction 2",
        "rate": 7.5,
        "vote_count": 1787
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
        "id": 634649,
        "original_title": "Spider-Man: No Way Home",
        "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        "popularity": 175.626,
        "poster_path": "/5weKu49pzJCt06OPpjvT80efnQj.jpg",
        "release_date": "2021-12-15",
        "title": "Spider-Man: No Way Home",
        "rate": 8,
        "vote_count": 18260
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/5OFUCydVG9cSS5hMk4A6XNt1oH4.jpg",
        "id": 1064835,
        "original_title": "七つの大罪 怨嗟のエジンバラ 後編",
        "overview": "Reunited with Lancelot for the first time since their tragic accident, Tristan must learn to conquer his inner demons in order to save his mother's life.",
        "popularity": 208.493,
        "poster_path": "/516MFML05KWiPfiQNAsVCGMySc7.jpg",
        "release_date": "2023-08-08",
        "title": "The Seven Deadly Sins: Grudge of Edinburgh Part 2",
        "rate": 7.5,
        "vote_count": 83
      },
      {
        "url": "https://image.tmdb.org/t/p/w500/5Jfk2p3iGrChUKkl0cBD5krr2u8.jpg",
        "id": 998731,
        "original_title": "映画 佐々木と宮野ー卒業編ー",
        "overview": "Miyano’s world of Boys’ Love manga turns to reality when chance leads him to Sasaki. Now, Sasaki wants to spend every opportunity with him.",
        "popularity": 173.066,
        "poster_path": "/xjZjNaUVF9mX7ekOL3lvBUi72eQ.jpg",
        "release_date": "2023-02-17",
        "title": "Sasaki and Miyano: Graduation",
        "rate": 6.3,
        "vote_count": 15
      }
];